### ISSUE TITLE
lower log level for distribution

### ISSUE THREAD

**Issue by christian-peters** [osiam/server#263]
at the moment everything ist logged into catalina.out 

would be great if you lower the loglevel for all versions which will be released under https://maven-repo.evolvis.org/releases/org/osiam/osiam-distribution/

maybe its possible too, to write in a separate logfile instead of pushing all data into the main log catalina.out

**Comment by tkrille** [comment]
Ok, I will disable the profiling and decrease the log level for auth- and resource-server.

**Comment by dacrome** [comment]
:+1:
