### ISSUE TITLE
 'classes' classifier in pom

### ISSUE THREAD

**Issue by jvmlet** [osiam/server#266]
Hello
Would you please add 'classes' classifier for both war projects so they will be available as raw classes ?
Thanks

**Comment by tkrille** [comment]
@jvmlet I will add this feature for you now.

**Comment by tkrille** [comment]
We are planning a release for today, but you can already try the latest snapshots:

* https://maven-repo.evolvis.org/snapshots/org/osiam/osiam-resource-server/1.4-SNAPSHOT/osiam-resource-server-1.4-20150429.091729-25-classes.jar
* https://maven-repo.evolvis.org/snapshots/org/osiam/osiam-auth-server/1.4-SNAPSHOT/osiam-auth-server-1.4-20150429.091626-25-classes.jar
