### ISSUE TITLE
Installationsanleitung funktioniert nicht

### ISSUE THREAD

**Issue by mirabilos** [osiam/server#276]
Hi ihrs,

ich gehe gerade die Installationsanleitung für VerA.web durch, die ein tuëndes OSIAM voraussetzt (warum auch immer…). Hierbei wird auf https://github.com/osiam/server/wiki/detailed_reference_installation verwiesen.

Im Abschnitt https://github.com/osiam/server/wiki/detailed_reference_installation#user-content-database-setup sind die Dateinamen falsch, ich habe da z.B: `osiam-server/osiam-resource-server/sql/init_ddl.sql`

Außerdem wird dort auf eine `init_data.sql` im auth-server verwiesen, die nicht existiert.

**Comment by mirabilos** [comment]
Mehr: Beispiel legt eine DB namens „osiam“ an, verwendet aber „ong“ als DB-Namen in der `/etc/osiam/resource-server.properties`.

**Comment by mirabilos** [comment]
On Thu, 2 Apr 2015, David Crome wrote:

> Database and username are in sync with the properties, now the wiki
> should be up-to-date. The init_data.sql was deleted in the

OK.

> BTW: To simplify the installation process we want to provide osiam
> docker images also for production use. If you like to play around with
> the our already created docker image, just check out our [docker

No, we’re not using Docker in production.

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by dacrome** [comment]
Please close this issue if the changes fix your bugs.

> No, we're not using Docker in production.

Sure, you don't have to, but you could :)

**Comment by tkrille** [comment]
@dacrome @mirabilos Any updates on this issue? Can we close this now?

**Comment by mirabilos** [comment]
On Tue, 28 Apr 2015, Thomas Krille wrote:

> @dacrome @mirabilos Any updates on this issue? Can we close this now?

I’ll answer this the next time I run through the installation
instructions, which is almost certainly within the next two
months, probably earlier.

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by tkrille** [comment]
Alright, I'm closing this now. Feel free to re-open (or create a new issue) if necessary.
